# Generated by Django 2.2.2 on 2019-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190619_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
