# Generated by Django 2.2.2 on 2019-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190620_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
