# Generated by Django 3.0.3 on 2020-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190730_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
