image: docker
services:
  - docker:dind    
test:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose -f test.yml up -d postgres
    - docker-compose -f test.yml up --exit-code-from datafrontend