version: '3'
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  datafrontend:
    build: .
    environment:
      ENVIRONMENT: 'test'
      DATA_PATH: '/data'
      
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: 5432
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    command: 'python manage.py test'
    volumes:
      - ./dashboard:/app
    links:
      - postgres
    depends_on:
      - postgres