from annotations.serializers.annotation import AnnotationSerializer
from annotations.serializers.annotation_boundingbox import AnnotationBoundingboxSerializer
from annotations.serializers.annotation_segmentation import AnnotationSegmentationSerializer