# Generated by Django 2.2.2 on 2019-06-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_auto_20190118_2013'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dataset_id',
        ),
        migrations.AddField(
            model_name='category',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset'),
            preserve_default=False,
        ),
    ]
