# Generated by Django 2.2.2 on 2019-06-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('categories', '0002_auto_20190619_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dataset',
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
