# Generated by Django 3.0.3 on 2020-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190620_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
