# Generated by Django 2.2.2 on 2019-06-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('images', '0001_initial'),
        ('annotations', '0002_annotationboundingbox_annotationsegmentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='image_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
            preserve_default=False,
        ),
    ]
