# Generated by Django 3.0.3 on 2020-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_auto_20190621_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='annotationboundingbox',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='annotationboundingbox',
            name='is_crowd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='is_crowd',
            field=models.BooleanField(default=False),
        ),
    ]
