# Generated by Django 3.0.3 on 2020-02-17 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_auto_20200216_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsegmentation',
            name='segmentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
