# Generated by Django 3.0.3 on 2020-02-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_annotationsegmentation_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationboundingbox',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
