# Generated by Django 3.0.3 on 2020-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_auto_20200218_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsegmentation',
            name='x_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='x_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='y_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotationsegmentation',
            name='y_min',
            field=models.FloatField(null=True),
        ),
    ]
