# Generated by Django 3.0.3 on 2020-02-21 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_auto_20200219_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationsegmentation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='annotationsegmentation',
            name='image',
        ),
        migrations.AddField(
            model_name='annotation',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_crowd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='mask',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='segmentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='annotation',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y_min',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='AnnotationBoundingbox',
        ),
        migrations.DeleteModel(
            name='AnnotationSegmentation',
        ),
    ]
