# Generated by Django 3.0.3 on 2020-02-22 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_auto_20200221_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='segmentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
