# Generated by Django 2.2.3 on 2019-07-30 18:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_batch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('ignore', 'ignore'), ('solved', 'solved')], default='open', max_length=150)),
                ('reason', models.CharField(choices=[('image_duplicate', 'Duplicate Image'), ('image_file_not_found', 'Image Not Found'), ('annotation_duplicate', 'Annotation overlapping'), ('annotation_boundingbox_duplicate', 'Boundingbox overlapping'), ('annotation_segmentation_duplicate', 'Segmentation overlapping')], max_length=150)),
                ('message', models.CharField(max_length=250, null=True)),
                ('affected_ids', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
